### ISSUE TITLE
Slide Mountain elevation is incorrect in basemap

### ISSUE THREAD

**Issue by balluanudeep** [stamen/maps.stamen.com#204] opened 2023-01-31 16:56 UTC
The Slide Mountain, Ulster County, NY is noted as “4200m”-this is incorrect. The elevation of said peak is 4,180 feet 

URL: http://maps.stamen.com/terrain/#9/42.0687/-74.2648

![image](https://user-images.githubusercontent.com/31974346/215829868-11f9e0b0-fb90-4a31-a8d9-6b4478e02a57.png)

**Comment by almccon** [comment] 2023-07-27 04:02
Thanks for the bug report! This is a duplicate of an issue in the Terrain repo: https://github.com/stamen/terrain-classic/issues/108. Basically, the data for mountain peaks comes from Natural Earth, and they fixed this bug many years ago, but we haven't updated the data for Terrain even longer.

However, we're currently in the process of completely updating all the data for our Terrain map and I can confirm that this bug will be gone in the next release (coming in a month or so).

**Closed by almccon** 2023-07-27 04:02 UTC
