### ISSUE TITLE
Harney Peak in South Dakota

### ISSUE THREAD

**Issue by eflowbeach** [stamen/maps.stamen.com#153] opened 2020-05-12 13:52 UTC
Hi,

In SW South Dakota in the Stamen Topo map, Harney Peak should be labeled as Black Elk Peak.
Apparently, this is a sensitive topic locally.

![image](https://user-images.githubusercontent.com/5221303/81699977-ab80b700-942d-11ea-9252-ad9d32888cda.png)

![image](https://user-images.githubusercontent.com/5221303/81700103-d5d27480-942d-11ea-8d0a-c560fa5d5003.png)

**Comment by almccon** [comment] 2021-02-17 00:01
Dupe of https://github.com/stamen/terrain-classic/issues/124

**Closed by almccon** 2021-02-17 00:01 UTC
